export interface Company {
  name: string;
  slug: string;
  oneLiner: string;
  batch: string;
  industry: string[];
  region: string;
  teamSize: number;
  isHiring: boolean;
  isNonprofit: boolean;
  isTopCompany: boolean;
  isBlackFounded: boolean;
  isWomenFounded: boolean;
  isHispanicLatinoFounded: boolean;
  logoUrl: string;
  category?: "featured" | "breakthrough";
}

export const COMPANIES: Company[] = [
  // ── 1기 ─────────────────────────────────────────
  {
    name: "플레이트잇",
    slug: "plate-it",
    oneLiner: "대학가 공유주방 플랫폼 — 누구나 셰프가 될 수 있는 Cloud Kitchen",
    batch: "1기",
    industry: ["푸드테크", "커머스"],
    region: "서울",
    teamSize: 6,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "스터디메이트",
    slug: "studymate",
    oneLiner: "AI 기반 학습 관리 서비스 — 내 공부 패턴을 분석하고 최적 루틴을 설계",
    batch: "1기",
    industry: ["에듀테크", "AI/ML"],
    region: "서울",
    teamSize: 5,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "링크드유",
    slug: "linked-u",
    oneLiner: "대학생 네트워킹 플랫폼 — 캠퍼스를 넘는 Career Connection",
    batch: "1기",
    industry: ["소셜", "에듀테크"],
    region: "서울",
    teamSize: 4,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "머니메이트",
    slug: "moneymate",
    oneLiner: "Z세대 맞춤 가계부 & 자산관리 앱 — 첫 월급부터 투자까지",
    batch: "1기",
    industry: ["핀테크"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "바이트사이즈",
    slug: "bytesize",
    oneLiner: "5분 마이크로러닝 콘텐츠 마켓플레이스 — 숏폼으로 배우는 실무 스킬",
    batch: "1기",
    industry: ["에듀테크", "커머스"],
    region: "서울",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=80&h=80&fit=crop",
  },
  {
    name: "캠퍼스딜",
    slug: "campus-deal",
    oneLiner: "대학생 전용 중고거래 & 공동구매 커머스",
    batch: "1기",
    industry: ["커머스", "소셜"],
    region: "수원/경기",
    teamSize: 4,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=80&h=80&fit=crop",
  },
  {
    name: "튜터링고",
    slug: "tutoringo",
    oneLiner: "대학생 과외 매칭 서비스 — 검증된 선배에게 1:1 과외를",
    batch: "1기",
    industry: ["에듀테크"],
    region: "서울",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=80&h=80&fit=crop",
  },

  // ── 2기 ─────────────────────────────────────────
  {
    name: "그린바이트",
    slug: "greenbite",
    oneLiner: "친환경 밀키트 구독 서비스 — Farm to Table, Zero Waste",
    batch: "2기",
    industry: ["푸드테크", "커머스"],
    region: "서울",
    teamSize: 7,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "펫닥터",
    slug: "pet-doctor",
    oneLiner: "반려동물 건강관리 앱 — AI 증상 체크부터 병원 예약까지",
    batch: "2기",
    industry: ["헬스케어", "AI/ML"],
    region: "서울",
    teamSize: 5,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "캠퍼스런",
    slug: "campus-run",
    oneLiner: "대학생 러닝 커뮤니티 — Run Together, Grow Together",
    batch: "2기",
    industry: ["헬스케어", "소셜"],
    region: "수원/경기",
    teamSize: 4,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "로컬잇",
    slug: "local-eat",
    oneLiner: "동네 소상공인 맛집 큐레이션 & 예약 플랫폼",
    batch: "2기",
    industry: ["푸드테크", "커머스"],
    region: "서울",
    teamSize: 5,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=80&h=80&fit=crop",
  },
  {
    name: "클래스팝",
    slug: "classpop",
    oneLiner: "원데이 클래스 예약 플랫폼 — 취미부터 Side Hustle까지",
    batch: "2기",
    industry: ["에듀테크", "커머스"],
    region: "서울",
    teamSize: 4,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=80&h=80&fit=crop",
  },
  {
    name: "데일리핏",
    slug: "dailyfit",
    oneLiner: "AI Personal Trainer — 홈트레이닝을 넘어선 맞춤 피트니스",
    batch: "2기",
    industry: ["헬스케어", "AI/ML"],
    region: "서울",
    teamSize: 5,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "룸메이트",
    slug: "roommate",
    oneLiner: "대학생 룸메이트 매칭 & 하우스쉐어 플랫폼",
    batch: "2기",
    industry: ["소셜"],
    region: "수원/경기",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=80&h=80&fit=crop",
  },
  {
    name: "프레시박스",
    slug: "freshbox",
    oneLiner: "새벽배송 농산물 D2C — 산지 직송 Fresh Produce",
    batch: "2기",
    industry: ["푸드테크", "물류"],
    region: "수원/경기",
    teamSize: 6,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=80&h=80&fit=crop",
  },

  // ── 3기 ─────────────────────────────────────────
  {
    name: "노트잇",
    slug: "note-it",
    oneLiner: "강의 노트 AI 요약 서비스 — Record, Summarize, Ace the Exam",
    batch: "3기",
    industry: ["에듀테크", "AI/ML"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=80&h=80&fit=crop",
    category: "featured",
  },
  {
    name: "팜잇",
    slug: "farm-it",
    oneLiner: "스마트팜 모니터링 SaaS — IoT 센서로 농장을 Data-Driven으로",
    batch: "3기",
    industry: ["SaaS", "AI/ML"],
    region: "기타",
    teamSize: 5,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "셔틀버디",
    slug: "shuttle-buddy",
    oneLiner: "대학생 통학 카풀 매칭 — 같은 방향, 같이 가자",
    batch: "3기",
    industry: ["물류", "소셜"],
    region: "수원/경기",
    teamSize: 4,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=80&h=80&fit=crop",
  },
  {
    name: "필체크",
    slug: "pillcheck",
    oneLiner: "영양제 맞춤 추천 & 복용 리마인더 — AI Supplement Advisor",
    batch: "3기",
    industry: ["헬스케어", "AI/ML"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "인턴브릿지",
    slug: "intern-bridge",
    oneLiner: "스타트업 인턴 매칭 플랫폼 — 대학생과 초기 스타트업을 잇다",
    batch: "3기",
    industry: ["SaaS", "소셜"],
    region: "서울",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=80&h=80&fit=crop",
  },
  {
    name: "카페로그",
    slug: "cafelog",
    oneLiner: "카페 리뷰 & 좌석 실시간 현황 앱 — 공부할 카페, 바로 찾기",
    batch: "3기",
    industry: ["소셜", "기타"],
    region: "서울",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=80&h=80&fit=crop",
  },
  {
    name: "워크스페이스",
    slug: "workspace",
    oneLiner: "프리랜서 & 소규모팀 공유오피스 예약 SaaS",
    batch: "3기",
    industry: ["SaaS", "커머스"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=80&h=80&fit=crop",
  },
  {
    name: "트립메이커",
    slug: "trip-maker",
    oneLiner: "AI 여행 일정 자동 생성 — 취향 맞춤 국내 여행 Planner",
    batch: "3기",
    industry: ["AI/ML", "커머스"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=80&h=80&fit=crop",
    category: "breakthrough",
  },
  {
    name: "핏커넥트",
    slug: "fitconnect",
    oneLiner: "운동 파트너 매칭 앱 — 혼자 하기 싫은 운동, Together",
    batch: "3기",
    industry: ["헬스케어", "소셜"],
    region: "수원/경기",
    teamSize: 3,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=80&h=80&fit=crop",
  },
  {
    name: "페이퍼리스",
    slug: "paperless",
    oneLiner: "소상공인 전자 영수증 & 정산 자동화 SaaS",
    batch: "3기",
    industry: ["핀테크", "SaaS"],
    region: "서울",
    teamSize: 4,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=80&h=80&fit=crop",
  },
];

export const BATCH_OPTIONS = [
  { value: "1기", label: "1기" },
  { value: "2기", label: "2기" },
  { value: "3기", label: "3기" },
];

export const INDUSTRY_OPTIONS = [
  "에듀테크",
  "푸드테크",
  "헬스케어",
  "핀테크",
  "커머스",
  "소셜",
  "SaaS",
  "물류",
  "AI/ML",
  "기타",
];

export const REGION_OPTIONS = [
  "서울",
  "수원/경기",
  "기타",
];

export function getTopCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany);
}

export function getFeaturedCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany && c.category === "featured");
}

export function getBreakthroughCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany && c.category === "breakthrough");
}
