export interface Company {
  name: string;
  slug: string;
  oneLiner: string;
  batch: string;
  industry: string[];
  region: string;
  teamSize: number;
  isHiring: boolean;
  isNonprofit: boolean;
  isTopCompany: boolean;
  isBlackFounded: boolean;
  isWomenFounded: boolean;
  isHispanicLatinoFounded: boolean;
  logoUrl: string;
  category?: "featured" | "breakthrough";
}

export const COMPANIES: Company[] = [
  {
    name: "Airbnb",
    slug: "airbnb",
    oneLiner: "Book accommodations around the world.",
    batch: "W09",
    industry: ["Travel", "Marketplace"],
    region: "San Francisco, CA",
    teamSize: 6000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/ee60f430e8cb6ae769306e9c35e9e8088c5e9ca7.png",
    category: "featured",
  },
  {
    name: "Stripe",
    slug: "stripe",
    oneLiner: "Payments infrastructure for the internet.",
    batch: "S09",
    industry: ["Fintech", "Payments"],
    region: "San Francisco, CA",
    teamSize: 8000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/d3d8709415d66b20be8a506cf19a07a1c1494d4b.png",
    category: "featured",
  },
  {
    name: "DoorDash",
    slug: "doordash",
    oneLiner: "Restaurant delivery service.",
    batch: "S13",
    industry: ["Delivery", "Marketplace"],
    region: "San Francisco, CA",
    teamSize: 16000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/0974e24a02daa3bfc3e8e76d0e41d74b5d8bd722.png",
    category: "featured",
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    oneLiner: "Buy, sell, and manage cryptocurrencies.",
    batch: "S12",
    industry: ["Fintech", "Crypto / Web3"],
    region: "San Francisco, CA",
    teamSize: 3700,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: true,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/3e41328e3e051b1b0e0c60a5291cf1d6b2e4fc3e.png",
    category: "featured",
  },
  {
    name: "Instacart",
    slug: "instacart",
    oneLiner: "Grocery delivery from local stores.",
    batch: "S12",
    industry: ["Delivery", "Marketplace"],
    region: "San Francisco, CA",
    teamSize: 10000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/39d21b67b0b3bf10efc4aab38c68876ba80d0e21.png",
    category: "featured",
  },
  {
    name: "Reddit",
    slug: "reddit",
    oneLiner: "The front page of the internet.",
    batch: "S05",
    industry: ["Consumer", "Social Media"],
    region: "San Francisco, CA",
    teamSize: 2000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/05084e58c48d6997f0d78ab1929d76e2dbbccfda.png",
    category: "featured",
  },
  {
    name: "Twitch",
    slug: "twitch",
    oneLiner: "Live streaming platform for gamers and creators.",
    batch: "W07",
    industry: ["Consumer", "Entertainment"],
    region: "San Francisco, CA",
    teamSize: 2500,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/479e89dd6c797b1c05c4ad5c41e26de38cdc5ab4.png",
    category: "featured",
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    oneLiner: "Sync and share files online and across computers.",
    batch: "S07",
    industry: ["SaaS", "Productivity"],
    region: "San Francisco, CA",
    teamSize: 2800,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/4b56671cbfa66d08d023be498f64101f78fc4e93.png",
    category: "featured",
  },
  {
    name: "GitLab",
    slug: "gitlab",
    oneLiner: "A complete DevOps platform, delivered as a single application.",
    batch: "W15",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 2000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/84a26679d8e29a1ea5e4cd00ed0e0a2f3fef0a7c.png",
    category: "featured",
  },
  {
    name: "Cruise",
    slug: "cruise",
    oneLiner: "Self-driving car technology.",
    batch: "W14",
    industry: ["Hard Tech", "Autonomous Vehicles"],
    region: "San Francisco, CA",
    teamSize: 2000,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/a31f5cf2327afb5c2397f1fa82a5352dc43d834d.png",
  },
  {
    name: "Brex",
    slug: "brex",
    oneLiner: "The AI-powered spend platform.",
    batch: "W17",
    industry: ["Fintech", "B2B"],
    region: "San Francisco, CA",
    teamSize: 1100,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: true,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/9a3a9cb74a3e7e7cb4b06d1659732df6d90e36da.png",
    category: "breakthrough",
  },
  {
    name: "Faire",
    slug: "faire",
    oneLiner: "Online wholesale marketplace.",
    batch: "W17",
    industry: ["Marketplace", "E-Commerce"],
    region: "San Francisco, CA",
    teamSize: 1000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/d6f0f5cf8f92e84e7e1b48cd96b0ba827f7c66e4.png",
    category: "breakthrough",
  },
  {
    name: "Zapier",
    slug: "zapier",
    oneLiner: "The easiest way to automate your work.",
    batch: "S12",
    industry: ["SaaS", "Productivity"],
    region: "San Francisco, CA",
    teamSize: 800,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/a33c06c8a0d55b1697d74f0c0843056c3367a468.png",
    category: "breakthrough",
  },
  {
    name: "Ginkgo Bioworks",
    slug: "ginkgo-bioworks",
    oneLiner: "The organism company — programming cells like we program computers.",
    batch: "S14",
    industry: ["Biotech", "Hard Tech"],
    region: "Boston, MA",
    teamSize: 900,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/bf0e90f2c81e7d1ac50a1da86c80764a4f62b45d.png",
    category: "breakthrough",
  },
  {
    name: "Podium",
    slug: "podium",
    oneLiner: "Communication and payments platform for local businesses.",
    batch: "W16",
    industry: ["SaaS", "B2B"],
    region: "Lehi, UT",
    teamSize: 1500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/d7d9dc95dd72c0e14e74c92a3c3ef8a79d97e0a3.png",
  },
  {
    name: "Segment",
    slug: "segment",
    oneLiner: "Customer data platform for collecting, cleaning, and controlling customer data.",
    batch: "S11",
    industry: ["SaaS", "Analytics"],
    region: "San Francisco, CA",
    teamSize: 600,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/a1e7d1e694eee17e54e3cf7b25dade8be7f27043.png",
  },
  {
    name: "Gusto",
    slug: "gusto",
    oneLiner: "Payroll, benefits, and HR for small businesses.",
    batch: "W12",
    industry: ["Fintech", "B2B"],
    region: "San Francisco, CA",
    teamSize: 2300,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/b127d4a2eec1be8f7e4fe92b6bbad0d0a5f2d75b.png",
    category: "breakthrough",
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    oneLiner: "Payment gateway for India.",
    batch: "W15",
    industry: ["Fintech", "Payments"],
    region: "Bangalore, India",
    teamSize: 3000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/15d48ef3dc8a1c979fdb1f6ff8a8c28f0aae3fce.png",
    category: "breakthrough",
  },
  {
    name: "Mattermost",
    slug: "mattermost",
    oneLiner: "Open source Slack alternative for enterprise.",
    batch: "S12",
    industry: ["SaaS", "Developer Tools"],
    region: "Palo Alto, CA",
    teamSize: 300,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/cb09482c18d5c5e0e9f3a17f2a9ab4c6b38a08e9.png",
  },
  {
    name: "Render",
    slug: "render",
    oneLiner: "A unified cloud to build and run all your apps and websites.",
    batch: "S19",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 150,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/d67e4f7c9e80f4f0b0e7f29c3e69fed1b7a4cde5.png",
  },
  {
    name: "Optimizely",
    slug: "optimizely",
    oneLiner: "Experimentation platform to test anything on your website.",
    batch: "W10",
    industry: ["SaaS", "Analytics"],
    region: "San Francisco, CA",
    teamSize: 1200,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/eb9fc36bd1e33dd4a5bb0844bfcdc94e923ed2a3.png",
  },
  {
    name: "Replit",
    slug: "replit",
    oneLiner: "Build software collaboratively from anywhere in the world.",
    batch: "W18",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 200,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/b7d7d4e65e1a6f0c3b44c0d7e8a5a9d6f3f2e1d0.png",
    category: "breakthrough",
  },
  {
    name: "Meesho",
    slug: "meesho",
    oneLiner: "Social commerce platform enabling small businesses in India.",
    batch: "W16",
    industry: ["E-Commerce", "Marketplace"],
    region: "Bangalore, India",
    teamSize: 2200,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/e8b0c9c4b7f1e0e6a3d4c5b2a9f8d7c6e5b4a3d2.png",
  },
  {
    name: "Monzo",
    slug: "monzo",
    oneLiner: "The bank of the future.",
    batch: "S16",
    industry: ["Fintech", "Banking"],
    region: "London, UK",
    teamSize: 3000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/2ddb0d0d1e5c2f4a5a6b7c8d9e0f1a2b3c4d5e6f.png",
    category: "breakthrough",
  },
  {
    name: "Watsi",
    slug: "watsi",
    oneLiner: "Fund healthcare for people around the world.",
    batch: "W13",
    industry: ["Healthcare", "Nonprofit"],
    region: "San Francisco, CA",
    teamSize: 10,
    isHiring: false,
    isNonprofit: true,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "https://bookface-images.s3.amazonaws.com/logos/d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4.png",
  },
  {
    name: "Rappi",
    slug: "rappi",
    oneLiner: "On-demand delivery app for Latin America.",
    batch: "W16",
    industry: ["Delivery", "Marketplace"],
    region: "San Francisco, CA",
    teamSize: 3500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: true,
    logoUrl: "",
  },
  {
    name: "Weave",
    slug: "weave",
    oneLiner: "Communication platform for small businesses.",
    batch: "W14",
    industry: ["SaaS", "B2B"],
    region: "Lehi, UT",
    teamSize: 1000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Convoy",
    slug: "convoy",
    oneLiner: "Digital freight network for trucking.",
    batch: "W15",
    industry: ["Marketplace", "B2B"],
    region: "San Francisco, CA",
    teamSize: 800,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Amplitude",
    slug: "amplitude",
    oneLiner: "Product analytics for the digital era.",
    batch: "W12",
    industry: ["SaaS", "Analytics"],
    region: "San Francisco, CA",
    teamSize: 700,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Webflow",
    slug: "webflow",
    oneLiner: "Visual web development platform.",
    batch: "S13",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 600,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Fivetran",
    slug: "fivetran",
    oneLiner: "Automated data integration.",
    batch: "W13",
    industry: ["SaaS", "Analytics"],
    region: "San Francisco, CA",
    teamSize: 700,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Flexport",
    slug: "flexport",
    oneLiner: "Platform for global trade and logistics.",
    batch: "W14",
    industry: ["B2B", "Marketplace"],
    region: "San Francisco, CA",
    teamSize: 2500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Embark Trucks",
    slug: "embark-trucks",
    oneLiner: "Self-driving technology for the trucking industry.",
    batch: "W16",
    industry: ["Hard Tech", "Autonomous Vehicles"],
    region: "San Francisco, CA",
    teamSize: 200,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "PlanGrid",
    slug: "plangrid",
    oneLiner: "Construction productivity software.",
    batch: "W12",
    industry: ["SaaS", "B2B"],
    region: "San Francisco, CA",
    teamSize: 300,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: true,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Vercel",
    slug: "vercel",
    oneLiner: "Develop. Preview. Ship. The platform for frontend developers.",
    batch: "W15",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 450,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
    category: "breakthrough",
  },
  {
    name: "LatchBio",
    slug: "latchbio",
    oneLiner: "The operating system for wet lab biologists.",
    batch: "W21",
    industry: ["Biotech", "SaaS"],
    region: "San Francisco, CA",
    teamSize: 80,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "PostHog",
    slug: "posthog",
    oneLiner: "Open-source product analytics.",
    batch: "W20",
    industry: ["SaaS", "Analytics"],
    region: "London, UK",
    teamSize: 50,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "OpenSea",
    slug: "opensea",
    oneLiner: "The largest NFT marketplace.",
    batch: "W18",
    industry: ["Marketplace", "Crypto / Web3"],
    region: "New York, NY",
    teamSize: 250,
    isHiring: false,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
    category: "breakthrough",
  },
  {
    name: "Ironclad",
    slug: "ironclad",
    oneLiner: "Digital contract management platform.",
    batch: "S15",
    industry: ["SaaS", "B2B"],
    region: "San Francisco, CA",
    teamSize: 500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Algolia",
    slug: "algolia",
    oneLiner: "Search and discovery APIs for websites and apps.",
    batch: "W14",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Benchling",
    slug: "benchling",
    oneLiner: "Cloud platform for biotech R&D.",
    batch: "S12",
    industry: ["Biotech", "SaaS"],
    region: "San Francisco, CA",
    teamSize: 500,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "CodeSignal",
    slug: "codesignal",
    oneLiner: "Technical assessment platform for hiring.",
    batch: "W16",
    industry: ["SaaS", "B2B"],
    region: "San Francisco, CA",
    teamSize: 300,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Pave",
    slug: "pave",
    oneLiner: "Real-time compensation data and planning.",
    batch: "W20",
    industry: ["Fintech", "B2B"],
    region: "San Francisco, CA",
    teamSize: 200,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
  {
    name: "Zepto",
    slug: "zepto",
    oneLiner: "10-minute grocery delivery in India.",
    batch: "W21",
    industry: ["Delivery", "E-Commerce"],
    region: "Bangalore, India",
    teamSize: 3000,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: true,
    isBlackFounded: false,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
    category: "breakthrough",
  },
  {
    name: "Railway",
    slug: "railway",
    oneLiner: "Infrastructure platform for deploying apps.",
    batch: "W20",
    industry: ["SaaS", "Developer Tools"],
    region: "San Francisco, CA",
    teamSize: 45,
    isHiring: true,
    isNonprofit: false,
    isTopCompany: false,
    isBlackFounded: true,
    isWomenFounded: false,
    isHispanicLatinoFounded: false,
    logoUrl: "",
  },
];

export const BATCH_OPTIONS = [
  "W25", "S25", "F24", "W24", "S24", "W23", "S23", "W22", "S22",
  "W21", "S21", "W20", "S20", "W19", "S19", "W18", "W17", "W16",
  "S16", "S15", "W15", "W14", "S14", "S13", "W13", "S12", "W12",
  "S11", "W10", "W09", "S09", "S07", "W07", "S05",
];

export const INDUSTRY_OPTIONS = [
  "B2B", "Fintech", "SaaS", "Consumer", "Healthcare", "Hard Tech",
  "Marketplace", "Developer Tools", "E-Commerce", "Payments",
  "Analytics", "Biotech", "Delivery", "Entertainment", "Travel",
  "Productivity", "Social Media", "Autonomous Vehicles", "Crypto / Web3",
  "Banking", "Nonprofit",
];

export const REGION_OPTIONS = [
  "San Francisco, CA", "New York, NY", "Boston, MA", "Palo Alto, CA",
  "Lehi, UT", "London, UK", "Bangalore, India",
];

export function getTopCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany);
}

export function getFeaturedCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany && c.category === "featured");
}

export function getBreakthroughCompanies(): Company[] {
  return COMPANIES.filter((c) => c.isTopCompany && c.category === "breakthrough");
}
