export interface Founder {
  id: number;
  name: string;
  slug: string;
  company: string;
  companySlug: string;
  batch: string;
  oneLiner: string;
  industry: string;
  location: string;
  isTopCompanyFounder: boolean;
  photoPlaceholder: string;
}

export const FOUNDERS: Founder[] = [
  {
    id: 1,
    name: "김서준",
    slug: "kim-seojun",
    company: "스터디메이트",
    companySlug: "studymate",
    batch: "1기",
    oneLiner: "AI 기반 맞춤형 학습 플랫폼을 만드는 창업가. GPT 튜터로 대학생 시험 대비를 혁신 중.",
    industry: "AI/ML",
    location: "서울 종로구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 2,
    name: "이하은",
    slug: "lee-haeun",
    company: "노트잇",
    companySlug: "noteit",
    batch: "2기",
    oneLiner: "대학 강의 노트를 공유하고 거래하는 에듀테크 팀 리더. 성균관대 내부 베타 테스트에서 월 3,000 거래 달성.",
    industry: "에듀테크",
    location: "서울 종로구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 3,
    name: "박현우",
    slug: "park-hyunwoo",
    company: "그린바이트",
    companySlug: "greenbite",
    batch: "2기",
    oneLiner: "못난이 농산물 직거래 커머스 공동창업자. 산지 직송으로 30% 저렴한 친환경 장보기 실현.",
    industry: "커머스",
    location: "서울 성북구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 4,
    name: "최유나",
    slug: "choi-yuna",
    company: "펫닥터",
    companySlug: "petdoctor",
    batch: "3기",
    oneLiner: "반려동물 원격 진료 헬스케어 스타트업 창업. 수의사 매칭으로 야간 응급 상담 서비스 운영 중.",
    industry: "헬스케어",
    location: "서울 강남구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 5,
    name: "정민재",
    slug: "jung-minjae",
    company: "링크드유",
    companySlug: "linkedyou",
    batch: "1기",
    oneLiner: "대학생 전용 네트워킹 SaaS 파운더. 동아리·학회 간 협업 허브로 40개 대학 도입.",
    industry: "SaaS",
    location: "서울 종로구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 6,
    name: "한소율",
    slug: "han-soyul",
    company: "페이런",
    companySlug: "payrun",
    batch: "3기",
    oneLiner: "대학생 소액 투자·저축 핀테크 앱 창업자. 용돈 관리부터 주식 소수점 투자까지.",
    industry: "핀테크",
    location: "서울 마포구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 7,
    name: "오준혁",
    slug: "oh-junhyuk",
    company: "밀키트나우",
    companySlug: "mealkitnow",
    batch: "1기",
    oneLiner: "1인 가구 맞춤 밀키트 구독 서비스 공동창업자. 자취생 특화 레시피로 월 구독자 5,000명 돌파.",
    industry: "푸드테크",
    location: "서울 관악구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 8,
    name: "윤서영",
    slug: "yoon-seoyoung",
    company: "캠퍼스런",
    companySlug: "campusrun",
    batch: "2기",
    oneLiner: "대학 캠퍼스 내 라스트마일 배달 물류 스타트업 CEO. 학생 라이더 네트워크로 15분 배달 실현.",
    industry: "물류",
    location: "수원 장안구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 9,
    name: "임태호",
    slug: "lim-taeho",
    company: "코드브릿지",
    companySlug: "codebridge",
    batch: "1기",
    oneLiner: "비전공자를 위한 코딩 교육 플랫폼 파운더. 커리큘럼 기반 학습으로 취업 연계율 78% 달성.",
    industry: "에듀테크",
    location: "서울 종로구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 10,
    name: "강지우",
    slug: "kang-jiwoo",
    company: "핏메이커",
    companySlug: "fitmaker",
    batch: "3기",
    oneLiner: "AI 퍼스널 트레이닝 앱 공동창업자. 카메라 자세 분석으로 홈트레이닝 코칭 제공.",
    industry: "헬스케어",
    location: "서울 강남구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 11,
    name: "송대현",
    slug: "song-daehyun",
    company: "셰어플리",
    companySlug: "shareply",
    batch: "2기",
    oneLiner: "대학생 물품 공유 소셜 플랫폼 창업자. 교재·전자기기·생활용품 대여로 소비 줄이기 실천.",
    industry: "소셜",
    location: "서울 성북구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 12,
    name: "배수빈",
    slug: "bae-subin",
    company: "데이터폴리오",
    companySlug: "datafolio",
    batch: "1기",
    oneLiner: "대학생·주니어 개발자 포트폴리오 자동 생성 SaaS CEO. GitHub 연동으로 이력서 자동화.",
    industry: "SaaS",
    location: "서울 마포구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 13,
    name: "조원빈",
    slug: "jo-wonbin",
    company: "팜잇",
    companySlug: "farmit",
    batch: "3기",
    oneLiner: "스마트팜 IoT 솔루션 공동창업자. 도시 농업과 데이터 기반 작물 관리 시스템 개발.",
    industry: "AI/ML",
    location: "수원 장안구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 14,
    name: "신예린",
    slug: "shin-yerin",
    company: "트래블메이트",
    companySlug: "travelmate",
    batch: "2기",
    oneLiner: "대학생 그룹 여행 매칭 소셜 서비스 파운더. 관심사 기반 동행자 찾기로 MAU 12,000 달성.",
    industry: "소셜",
    location: "서울 종로구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 15,
    name: "황도윤",
    slug: "hwang-doyun",
    company: "클래스팝",
    companySlug: "classpop",
    batch: "1기",
    oneLiner: "원데이 클래스 예약 커머스 플랫폼 CEO. 공방·요리·운동 등 취미 클래스 700개 입점.",
    industry: "커머스",
    location: "서울 마포구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 16,
    name: "문채원",
    slug: "moon-chaewon",
    company: "리포트랩",
    companySlug: "reportlab",
    batch: "3기",
    oneLiner: "AI 보고서 작성 보조 도구 공동창업자. 학술 논문·과제 리포트 구조화를 자동화.",
    industry: "AI/ML",
    location: "서울 종로구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 17,
    name: "류건우",
    slug: "ryu-gunwoo",
    company: "쿡메이트",
    companySlug: "cookmate",
    batch: "2기",
    oneLiner: "냉장고 재료 기반 레시피 추천 푸드테크 창업자. 음식물 쓰레기 감소 캠페인 병행.",
    industry: "푸드테크",
    location: "서울 관악구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 18,
    name: "장하린",
    slug: "jang-harin",
    company: "머니버디",
    companySlug: "moneybuddy",
    batch: "1기",
    oneLiner: "Z세대 금융 리터러시 교육 핀테크 CEO. 게이미피케이션으로 재무 습관 만들기.",
    industry: "핀테크",
    location: "서울 강남구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 19,
    name: "안지호",
    slug: "ahn-jiho",
    company: "파슬로지",
    companySlug: "parcelogy",
    batch: "3기",
    oneLiner: "택배 실시간 추적·리뷰 물류 플랫폼 파운더. 배송 예측 AI로 수령 시간 정확도 92%.",
    industry: "물류",
    location: "서울 성북구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 20,
    name: "서윤아",
    slug: "seo-yuna",
    company: "튜터링크",
    companySlug: "tutorlink",
    batch: "2기",
    oneLiner: "대학원생-학부생 과외 매칭 에듀테크 공동창업자. 학과별 전공 튜터 500명 확보.",
    industry: "에듀테크",
    location: "수원 장안구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 21,
    name: "권태민",
    slug: "kwon-taemin",
    company: "인사이트랩",
    companySlug: "insightlab",
    batch: "1기",
    oneLiner: "소상공인 매출 분석 SaaS 창업자. POS 데이터 연동으로 매출 트렌드 리포트 자동 생성.",
    industry: "SaaS",
    location: "서울 마포구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 22,
    name: "나은서",
    slug: "na-eunseo",
    company: "그린바이트",
    companySlug: "greenbite",
    batch: "2기",
    oneLiner: "그린바이트 공동창업자 겸 마케팅 총괄. 로컬 농가 브랜딩과 SNS 바이럴 전략 담당.",
    industry: "커머스",
    location: "서울 성북구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 23,
    name: "유재원",
    slug: "yu-jaewon",
    company: "캠퍼스런",
    companySlug: "campusrun",
    batch: "2기",
    oneLiner: "캠퍼스런 CTO 겸 공동창업자. 실시간 라이더 배치 알고리즘과 물류 최적화 개발.",
    industry: "물류",
    location: "수원 장안구",
    isTopCompanyFounder: false,
    photoPlaceholder: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=160&h=160&fit=crop&crop=face",
  },
  {
    id: 24,
    name: "차민서",
    slug: "cha-minseo",
    company: "스터디메이트",
    companySlug: "studymate",
    batch: "1기",
    oneLiner: "스터디메이트 공동창업자 겸 CPO. 학습 데이터 기반 커리큘럼 개인화 설계 담당.",
    industry: "AI/ML",
    location: "서울 종로구",
    isTopCompanyFounder: true,
    photoPlaceholder: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=160&h=160&fit=crop&crop=face",
  },
];

export const BATCH_OPTIONS = [
  "1기",
  "2기",
  "3기",
];

export const INDUSTRY_OPTIONS = [
  "에듀테크",
  "푸드테크",
  "헬스케어",
  "핀테크",
  "커머스",
  "소셜",
  "SaaS",
  "물류",
  "AI/ML",
];

export const LOCATION_OPTIONS = [
  "서울 종로구",
  "서울 성북구",
  "서울 강남구",
  "서울 마포구",
  "서울 관악구",
  "수원 장안구",
];
