export interface Founder {
  id: number;
  name: string;
  slug: string;
  company: string;
  companySlug: string;
  batch: string;
  oneLiner: string;
  industry: string;
  location: string;
  isTopCompanyFounder: boolean;
  photoPlaceholder: string;
}

export const FOUNDERS: Founder[] = [
  {
    id: 1,
    name: "Brian Chesky",
    slug: "brian-chesky",
    company: "Airbnb",
    companySlug: "airbnb",
    batch: "W09",
    oneLiner: "Co-founder & CEO of Airbnb, the global travel marketplace",
    industry: "Marketplace",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "BC",
  },
  {
    id: 2,
    name: "Patrick Collison",
    slug: "patrick-collison",
    company: "Stripe",
    companySlug: "stripe",
    batch: "S09",
    oneLiner: "Co-founder & CEO of Stripe, internet payments infrastructure",
    industry: "Fintech",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "PC",
  },
  {
    id: 3,
    name: "John Collison",
    slug: "john-collison",
    company: "Stripe",
    companySlug: "stripe",
    batch: "S09",
    oneLiner: "Co-founder & President of Stripe",
    industry: "Fintech",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "JC",
  },
  {
    id: 4,
    name: "Drew Houston",
    slug: "drew-houston",
    company: "Dropbox",
    companySlug: "dropbox",
    batch: "S07",
    oneLiner: "Co-founder & CEO of Dropbox, cloud file storage and sharing",
    industry: "SaaS",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "DH",
  },
  {
    id: 5,
    name: "Arash Ferdowsi",
    slug: "arash-ferdowsi",
    company: "Dropbox",
    companySlug: "dropbox",
    batch: "S07",
    oneLiner: "Co-founder of Dropbox",
    industry: "SaaS",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "AF",
  },
  {
    id: 6,
    name: "Sam Altman",
    slug: "sam-altman",
    company: "OpenAI",
    companySlug: "openai",
    batch: "S05",
    oneLiner: "CEO of OpenAI, former President of Y Combinator",
    industry: "AI",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "SA",
  },
  {
    id: 7,
    name: "Tony Xu",
    slug: "tony-xu",
    company: "DoorDash",
    companySlug: "doordash",
    batch: "S13",
    oneLiner: "Co-founder & CEO of DoorDash, food delivery platform",
    industry: "Marketplace",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "TX",
  },
  {
    id: 8,
    name: "Henrique Dubugras",
    slug: "henrique-dubugras",
    company: "Brex",
    companySlug: "brex",
    batch: "W17",
    oneLiner: "Co-founder & CEO of Brex, corporate cards for startups",
    industry: "Fintech",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "HD",
  },
  {
    id: 9,
    name: "Pedro Franceschi",
    slug: "pedro-franceschi",
    company: "Brex",
    companySlug: "brex",
    batch: "W17",
    oneLiner: "Co-founder & CTO of Brex",
    industry: "Fintech",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "PF",
  },
  {
    id: 10,
    name: "David Velez",
    slug: "david-velez",
    company: "Nubank",
    companySlug: "nubank",
    batch: "S13",
    oneLiner: "Founder & CEO of Nubank, digital banking in Latin America",
    industry: "Fintech",
    location: "Sao Paulo, Brazil",
    isTopCompanyFounder: true,
    photoPlaceholder: "DV",
  },
  {
    id: 11,
    name: "Justin Kan",
    slug: "justin-kan",
    company: "Twitch",
    companySlug: "twitch",
    batch: "W07",
    oneLiner: "Co-founder of Twitch (acquired by Amazon for $970M)",
    industry: "Media",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "JK",
  },
  {
    id: 12,
    name: "Emmett Shear",
    slug: "emmett-shear",
    company: "Twitch",
    companySlug: "twitch",
    batch: "W07",
    oneLiner: "Co-founder & former CEO of Twitch",
    industry: "Media",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "ES",
  },
  {
    id: 13,
    name: "Alexandr Wang",
    slug: "alexandr-wang",
    company: "Scale AI",
    companySlug: "scale-ai",
    batch: "S16",
    oneLiner: "Founder & CEO of Scale AI, AI training data platform",
    industry: "AI",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "AW",
  },
  {
    id: 14,
    name: "Amjad Masad",
    slug: "amjad-masad",
    company: "Replit",
    companySlug: "replit",
    batch: "W18",
    oneLiner: "Founder & CEO of Replit, collaborative coding platform",
    industry: "Devtools",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "AM",
  },
  {
    id: 15,
    name: "Guillermo Rauch",
    slug: "guillermo-rauch",
    company: "Vercel",
    companySlug: "vercel",
    batch: "W21",
    oneLiner: "Founder & CEO of Vercel, frontend cloud platform",
    industry: "Devtools",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "GR",
  },
  {
    id: 16,
    name: "Vlad Tenev",
    slug: "vlad-tenev",
    company: "Robinhood",
    companySlug: "robinhood",
    batch: "S13",
    oneLiner: "Co-founder & CEO of Robinhood, commission-free trading",
    industry: "Fintech",
    location: "Menlo Park, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "VT",
  },
  {
    id: 17,
    name: "Baiju Bhatt",
    slug: "baiju-bhatt",
    company: "Robinhood",
    companySlug: "robinhood",
    batch: "S13",
    oneLiner: "Co-founder of Robinhood",
    industry: "Fintech",
    location: "Menlo Park, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "BB",
  },
  {
    id: 18,
    name: "Apoorva Mehta",
    slug: "apoorva-mehta",
    company: "Instacart",
    companySlug: "instacart",
    batch: "S12",
    oneLiner: "Founder of Instacart, grocery delivery platform",
    industry: "Marketplace",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "APM",
  },
  {
    id: 19,
    name: "Tracy Young",
    slug: "tracy-young",
    company: "PlanGrid",
    companySlug: "plangrid",
    batch: "W12",
    oneLiner: "Co-founder & former CEO of PlanGrid (acquired by Autodesk for $875M)",
    industry: "Construction Tech",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "TY",
  },
  {
    id: 20,
    name: "Gustav Soderstrom",
    slug: "gustav-soderstrom",
    company: "Mapillary",
    companySlug: "mapillary",
    batch: "W15",
    oneLiner: "Co-founder of Mapillary (acquired by Meta)",
    industry: "AI",
    location: "Malmö, Sweden",
    isTopCompanyFounder: false,
    photoPlaceholder: "GS",
  },
  {
    id: 21,
    name: "Harj Taggar",
    slug: "harj-taggar",
    company: "Triplebyte",
    companySlug: "triplebyte",
    batch: "S15",
    oneLiner: "Co-founder & CEO of Triplebyte, technical recruiting platform",
    industry: "B2B",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "HT",
  },
  {
    id: 22,
    name: "Tom Preston-Werner",
    slug: "tom-preston-werner",
    company: "GitHub",
    companySlug: "github",
    batch: "S08",
    oneLiner: "Co-founder of GitHub (acquired by Microsoft for $7.5B)",
    industry: "Devtools",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "TPW",
  },
  {
    id: 23,
    name: "Wade Foster",
    slug: "wade-foster",
    company: "Zapier",
    companySlug: "zapier",
    batch: "S12",
    oneLiner: "Co-founder & CEO of Zapier, workflow automation platform",
    industry: "SaaS",
    location: "Remote",
    isTopCompanyFounder: true,
    photoPlaceholder: "WF",
  },
  {
    id: 24,
    name: "Christina Cacioppo",
    slug: "christina-cacioppo",
    company: "Vanta",
    companySlug: "vanta",
    batch: "W18",
    oneLiner: "Founder & CEO of Vanta, automated security compliance",
    industry: "B2B",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "CC",
  },
  {
    id: 25,
    name: "Mathilde Collin",
    slug: "mathilde-collin",
    company: "Front",
    companySlug: "front",
    batch: "S14",
    oneLiner: "Co-founder & CEO of Front, customer communication hub",
    industry: "SaaS",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "MC",
  },
  {
    id: 26,
    name: "Sid Sijbrandij",
    slug: "sid-sijbrandij",
    company: "GitLab",
    companySlug: "gitlab",
    batch: "W15",
    oneLiner: "Co-founder & CEO of GitLab, complete DevOps platform",
    industry: "Devtools",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "SS",
  },
  {
    id: 27,
    name: "Immad Akhund",
    slug: "immad-akhund",
    company: "Mercury",
    companySlug: "mercury",
    batch: "S19",
    oneLiner: "Founder & CEO of Mercury, banking for startups",
    industry: "Fintech",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "IA",
  },
  {
    id: 28,
    name: "Jared Friedman",
    slug: "jared-friedman",
    company: "Scribd",
    companySlug: "scribd",
    batch: "S06",
    oneLiner: "Co-founder of Scribd, YC Partner",
    industry: "Media",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "JF",
  },
  {
    id: 29,
    name: "Kevin Hale",
    slug: "kevin-hale",
    company: "Wufoo",
    companySlug: "wufoo",
    batch: "W06",
    oneLiner: "Co-founder of Wufoo (acquired by SurveyMonkey), YC Partner",
    industry: "SaaS",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "KH",
  },
  {
    id: 30,
    name: "Nicolas Dessaigne",
    slug: "nicolas-dessaigne",
    company: "Algolia",
    companySlug: "algolia",
    batch: "W14",
    oneLiner: "Co-founder of Algolia, search-as-a-service platform",
    industry: "SaaS",
    location: "Paris, France",
    isTopCompanyFounder: false,
    photoPlaceholder: "ND",
  },
  {
    id: 31,
    name: "Harshil Mathur",
    slug: "harshil-mathur",
    company: "Razorpay",
    companySlug: "razorpay",
    batch: "W15",
    oneLiner: "Co-founder & CEO of Razorpay, India's leading payments platform",
    industry: "Fintech",
    location: "Bangalore, India",
    isTopCompanyFounder: true,
    photoPlaceholder: "HM",
  },
  {
    id: 32,
    name: "Max Mullen",
    slug: "max-mullen",
    company: "Instacart",
    companySlug: "instacart",
    batch: "S12",
    oneLiner: "Co-founder of Instacart",
    industry: "Marketplace",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "MM",
  },
  {
    id: 33,
    name: "Josh Browder",
    slug: "josh-browder",
    company: "DoNotPay",
    companySlug: "donotpay",
    batch: "S16",
    oneLiner: "Founder & CEO of DoNotPay, the world's first robot lawyer",
    industry: "AI",
    location: "San Francisco, CA",
    isTopCompanyFounder: false,
    photoPlaceholder: "JB",
  },
  {
    id: 34,
    name: "Tiffani Ashley Bell",
    slug: "tiffani-ashley-bell",
    company: "The Human Utility",
    companySlug: "the-human-utility",
    batch: "W16",
    oneLiner: "Founder of The Human Utility, helping families with water bills",
    industry: "Nonprofit",
    location: "Detroit, MI",
    isTopCompanyFounder: false,
    photoPlaceholder: "TB",
  },
  {
    id: 35,
    name: "Ivan Zhao",
    slug: "ivan-zhao",
    company: "Notion",
    companySlug: "notion",
    batch: "S13",
    oneLiner: "Co-founder & CEO of Notion, all-in-one workspace",
    industry: "SaaS",
    location: "San Francisco, CA",
    isTopCompanyFounder: true,
    photoPlaceholder: "IZ",
  },
];

export const BATCH_OPTIONS = [
  "W06",
  "S05",
  "S06",
  "S07",
  "W07",
  "S08",
  "W09",
  "S09",
  "S10",
  "S11",
  "W12",
  "S12",
  "S13",
  "W13",
  "S14",
  "W14",
  "W15",
  "S15",
  "S16",
  "W16",
  "W17",
  "W18",
  "S19",
  "W20",
  "W21",
];

export const INDUSTRY_OPTIONS = [
  "AI",
  "B2B",
  "Construction Tech",
  "Devtools",
  "Fintech",
  "Marketplace",
  "Media",
  "Nonprofit",
  "SaaS",
];

export const LOCATION_OPTIONS = [
  "San Francisco, CA",
  "Menlo Park, CA",
  "Sao Paulo, Brazil",
  "Malmö, Sweden",
  "Remote",
  "Paris, France",
  "Bangalore, India",
  "Detroit, MI",
];
