export interface Launch {
  id: number;
  company: string;
  slug: string;
  tagline: string;
  description: string;
  category: string;
  batch: string;
  votes: number;
  datePosted: string;
  daysAgo: number;
}

export const LAUNCHES: Launch[] = [
  {
    id: 1,
    company: "Stripe",
    slug: "stripe",
    tagline: "Payments infrastructure for the internet",
    description:
      "Stripe builds the most powerful and flexible tools for internet commerce. Whether you're creating a subscription service, an on-demand marketplace, an e-commerce store, or a crowdfunding platform, Stripe's meticulously designed APIs and unmatched functionality help you create the best possible product for your users.",
    category: "Fintech",
    batch: "S09",
    votes: 1842,
    datePosted: "2024-03-15",
    daysAgo: 2,
  },
  {
    id: 2,
    company: "Airbnb",
    slug: "airbnb",
    tagline: "Book unique homes and experiences",
    description:
      "Airbnb is a trusted community marketplace for people to list, discover, and book unique accommodations around the world — online or from a mobile phone. Whether an apartment for a night, a castle for a week, or a villa for a month, Airbnb connects people to unique travel experiences at any price point.",
    category: "Marketplace",
    batch: "W09",
    votes: 1567,
    datePosted: "2024-03-14",
    daysAgo: 3,
  },
  {
    id: 3,
    company: "Dropbox",
    slug: "dropbox",
    tagline: "Simplify your life with cloud storage",
    description:
      "Dropbox lets you bring all your photos, docs, and videos anywhere and share them easily. Access any file you save to your Dropbox from all your computers, phones, and tablets. With Dropbox, everything stays in sync automatically.",
    category: "SaaS",
    batch: "S07",
    votes: 1203,
    datePosted: "2024-03-13",
    daysAgo: 4,
  },
  {
    id: 4,
    company: "Brex",
    slug: "brex",
    tagline: "Corporate cards for startups",
    description:
      "Brex is reimagining financial systems so every growing company can realize their full potential. As the financial OS, Brex empowers the next generation of businesses with integrated corporate cards, banking, and spend management software.",
    category: "Fintech",
    batch: "W17",
    votes: 987,
    datePosted: "2024-03-12",
    daysAgo: 5,
  },
  {
    id: 5,
    company: "Retool",
    slug: "retool",
    tagline: "Build internal tools remarkably fast",
    description:
      "Retool is the fast way to build internal tools. Drag-and-drop building blocks and connect them to your databases and APIs to build your own custom internal tools in minutes. Connects with Postgres, REST APIs, GraphQL, Firebase, Google Sheets, and more.",
    category: "Devtools",
    batch: "W17",
    votes: 876,
    datePosted: "2024-03-12",
    daysAgo: 5,
  },
  {
    id: 6,
    company: "Posthog",
    slug: "posthog",
    tagline: "Open source product analytics",
    description:
      "PostHog is the all-in-one platform for building better products. It provides product analytics, session replay, feature flags, A/B testing, and surveys — all in one place. Self-serve, open-source, and built for developers who want full control of their data.",
    category: "Devtools",
    batch: "W20",
    votes: 834,
    datePosted: "2024-03-11",
    daysAgo: 6,
  },
  {
    id: 7,
    company: "Coinbase",
    slug: "coinbase",
    tagline: "Buy and sell cryptocurrency",
    description:
      "Coinbase is a secure platform that makes it easy to buy, sell, and store cryptocurrency like Bitcoin, Ethereum, and more. Based in the US, Coinbase is available in over 100 countries and has 110+ million verified users.",
    category: "Cryptocurrency",
    batch: "S12",
    votes: 756,
    datePosted: "2024-03-10",
    daysAgo: 7,
  },
  {
    id: 8,
    company: "Instacart",
    slug: "instacart",
    tagline: "Groceries delivered in as little as 1 hour",
    description:
      "Instacart delivers groceries from local stores in as little as 1 hour. Choose from your favorite local stores, browse their aisles, and get everything delivered right to your door. Available in 14,000+ cities across the US and Canada.",
    category: "Marketplace",
    batch: "S12",
    votes: 698,
    datePosted: "2024-03-09",
    daysAgo: 8,
  },
  {
    id: 9,
    company: "Zapier",
    slug: "zapier",
    tagline: "Automate your work across 5,000+ apps",
    description:
      "Zapier makes it easy to automate tasks between web apps. It moves info between your web apps automatically, so you can focus on your most important work. Define Zaps — automated workflows — that connect your apps and services together.",
    category: "SaaS",
    batch: "S12",
    votes: 645,
    datePosted: "2024-03-08",
    daysAgo: 9,
  },
  {
    id: 10,
    company: "Replit",
    slug: "replit",
    tagline: "Build software collaboratively from anywhere",
    description:
      "Replit is a collaborative browser-based IDE where you can code in 50+ programming languages without spending a second on setup. Start coding instantly, right from your browser, and collaborate in real-time with others. AI-powered coding assistant included.",
    category: "Devtools",
    batch: "W18",
    votes: 612,
    datePosted: "2024-03-07",
    daysAgo: 10,
  },
  {
    id: 11,
    company: "Gusto",
    slug: "gusto",
    tagline: "Payroll, benefits, and HR for modern businesses",
    description:
      "Gusto provides a modern, easy-to-use payroll, benefits, and HR platform for small businesses. Full-service payroll, health insurance administration, 401(k), workers' comp, and more — all in one place. Trusted by over 300,000 businesses.",
    category: "B2B",
    batch: "W12",
    votes: 578,
    datePosted: "2024-03-06",
    daysAgo: 11,
  },
  {
    id: 12,
    company: "Segment",
    slug: "segment",
    tagline: "Customer data platform for every team",
    description:
      "Segment is a customer data platform that collects, cleans, and controls your customer data. Collect events from your web and mobile apps, then send them to your analytics, marketing, and data warehousing tools with the flip of a switch.",
    category: "B2B",
    batch: "S11",
    votes: 534,
    datePosted: "2024-03-05",
    daysAgo: 12,
  },
  {
    id: 13,
    company: "Vercel",
    slug: "vercel",
    tagline: "Develop. Preview. Ship.",
    description:
      "Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. Vercel enables teams to iterate quickly and develop, preview, and ship delightful user experiences.",
    category: "Devtools",
    batch: "W21",
    votes: 501,
    datePosted: "2024-03-04",
    daysAgo: 13,
  },
  {
    id: 14,
    company: "Scale AI",
    slug: "scale-ai",
    tagline: "Accelerate the development of AI applications",
    description:
      "Scale AI provides high-quality training data for AI applications. Our platform combines machine learning with human review to deliver labeled datasets that power self-driving cars, language models, robotics, and more at enterprise scale.",
    category: "AI",
    batch: "S16",
    votes: 489,
    datePosted: "2024-03-03",
    daysAgo: 14,
  },
  {
    id: 15,
    company: "Pagerduty",
    slug: "pagerduty",
    tagline: "Real-time operations and incident management",
    description:
      "PagerDuty is a digital operations management platform that helps teams detect and resolve critical issues in real time. Integrating with 700+ tools, PagerDuty enables DevOps, IT, and business teams to drive operational excellence.",
    category: "SaaS",
    batch: "S10",
    votes: 467,
    datePosted: "2024-03-02",
    daysAgo: 15,
  },
  {
    id: 16,
    company: "Razorpay",
    slug: "razorpay",
    tagline: "Payment gateway for India",
    description:
      "Razorpay is India's leading full-stack financial solutions company. Their product suite allows businesses to accept, process, and disburse payments with its product suite. Powering payments for over 10 million businesses across India.",
    category: "Fintech",
    batch: "W15",
    votes: 445,
    datePosted: "2024-03-01",
    daysAgo: 16,
  },
  {
    id: 17,
    company: "GitLab",
    slug: "gitlab",
    tagline: "The complete DevOps platform",
    description:
      "GitLab is a web-based DevOps lifecycle tool that provides a Git repository manager providing wiki, issue-tracking, and continuous integration and deployment pipeline features. A single application for the entire software development lifecycle.",
    category: "Devtools",
    batch: "W15",
    votes: 423,
    datePosted: "2024-02-28",
    daysAgo: 17,
  },
  {
    id: 18,
    company: "Webflow",
    slug: "webflow",
    tagline: "Build production websites visually",
    description:
      "Webflow empowers designers to build professional, custom websites in a completely visual canvas with no code — while generating clean, production-ready code behind the scenes. CMS, hosting, and e-commerce built in.",
    category: "Design",
    batch: "W13",
    votes: 398,
    datePosted: "2024-02-27",
    daysAgo: 18,
  },
  {
    id: 19,
    company: "Rappi",
    slug: "rappi",
    tagline: "On-demand delivery for everything",
    description:
      "Rappi is a technology company that connects users to an ecosystem of products and services. From restaurant food delivery and groceries to pharmacy and cash withdrawals, Rappi brings convenience to millions across Latin America.",
    category: "Marketplace",
    batch: "W16",
    votes: 376,
    datePosted: "2024-02-26",
    daysAgo: 19,
  },
  {
    id: 20,
    company: "Monzo",
    slug: "monzo",
    tagline: "Banking made easy",
    description:
      "Monzo is a digital bank on a mission to make money work for everyone. With instant notifications, budgeting tools, and fee-free spending abroad, Monzo is building the bank of the future from the ground up. Over 8 million customers in the UK.",
    category: "Fintech",
    batch: "S16",
    votes: 354,
    datePosted: "2024-02-25",
    daysAgo: 20,
  },
  {
    id: 21,
    company: "Openai",
    slug: "openai",
    tagline: "AI research and deployment",
    description:
      "OpenAI is an AI research and deployment company. Their mission is to ensure that artificial general intelligence benefits all of humanity. They produce cutting-edge research and build safe, beneficial AI systems like GPT-4 and DALL-E.",
    category: "AI",
    batch: "YC",
    votes: 2103,
    datePosted: "2024-03-16",
    daysAgo: 1,
  },
  {
    id: 22,
    company: "DoorDash",
    slug: "doordash",
    tagline: "Food delivery to your door",
    description:
      "DoorDash is a technology company that connects consumers with their favorite local and national businesses. Founded in 2013 by Stanford students, DoorDash has grown to be the largest food delivery platform in the United States.",
    category: "Marketplace",
    batch: "S13",
    votes: 712,
    datePosted: "2024-03-09",
    daysAgo: 8,
  },
  {
    id: 23,
    company: "Faire",
    slug: "faire",
    tagline: "Online wholesale marketplace",
    description:
      "Faire is an online wholesale marketplace that connects independent retailers with unique brands at wholesale prices. Discover products from over 100,000 brands across home decor, beauty, food & drink, clothing, and more.",
    category: "Marketplace",
    batch: "W17",
    votes: 489,
    datePosted: "2024-03-03",
    daysAgo: 14,
  },
  {
    id: 24,
    company: "Algolia",
    slug: "algolia",
    tagline: "Search and discovery API",
    description:
      "Algolia provides a hosted search API that delivers instant and relevant results from the first keystroke. Powers search for over 17,000 companies including Stripe, Slack, Medium, and Twitch with sub-10ms response times.",
    category: "SaaS",
    batch: "W14",
    votes: 401,
    datePosted: "2024-02-28",
    daysAgo: 17,
  },
];

export const CATEGORIES = [
  { emoji: "all", label: "All" },
  { emoji: "🧠", label: "AI" },
  { emoji: "📊", label: "B2B" },
  { emoji: "🍃", label: "Climate" },
  { emoji: "💸", label: "Cryptocurrency" },
  { emoji: "🎓", label: "Education" },
  { emoji: "✏️", label: "Design" },
  { emoji: "⚒️", label: "Devtools" },
  { emoji: "🏦", label: "Fintech" },
  { emoji: "🛒", label: "Marketplace" },
  { emoji: "🖥️", label: "SaaS" },
];
